if [ "$TERM" != "dumb" ]; then
    alias ls='ls -GF'
    alias ll='ls -l'
fi
alias ps?='ps waux |grep'
alias rmr='rm -r'
alias ..='cd ..;'
alias ...='.. ..'
alias la='ls -lAohF'
alias rm_ds='find . -name .DS_Store -exec rm {} \;'
alias vim='mvim -v'
alias e='vim'
alias cp='cp -i'
alias rm='rm -i'
alias mv='mv -i'
alias mkdir='mkdir -p'
alias md='mkdir'
